### ISSUE TITLE
cheevor breaks

### ISSUE THREAD

**Issue by kevinejoyce** [roj42/nnnslackbot#6]
I typed "cheevor jumping puzzles" but i have all jumping puzzles completed. Lessy stopped responding after that.

**Comment by roj42** [comment]
This is fixed in 2.18.45. It was sitting in an infinite loop, since I assumed you'd always have at least one undone achievement. It's also faster now. Not that we can tell with our weak human eyes.

**Comment by nan0fr0g** [comment]
Saweet!
